name: Auto Approve Review

on:
  issue_comment:
    types: [created, edited]

jobs:
  auto-approve:
    name: PR Comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/github-script@v7
        name: Approve LGTM Review
        if: contains(github.event.comment.body, 'LGTM')
        with:
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              review_id: 1,
              event: 'APPROVE',
              body: 'Let`s get this merged then.'
            })
